"""Gemini API LLM-assisted patch generator for complex resource leak findings.

Uses Google Gemini API to generate minimal unified diff patches for findings
where automated AST template rewriter is not applicable.
"""

from __future__ import annotations

import os
from typing import Optional
from dotenv import load_dotenv

from google import genai
from src.models import Finding
from src.patch.diff_writer import generate_patch


load_dotenv()


def generate_llm_patch(
    file_path: str,
    source_bytes: bytes,
    finding: Finding,
) -> Optional[str]:
    """Generate a patch suggestion using Google Gemini API.

    Args:
        file_path: Path to the source file.
        source_bytes: File content bytes.
        finding: Leak finding details.

    Returns:
        Unified diff string generated by Gemini, or None if API unavailable.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        client = genai.Client(api_key=api_key)
        source_text = source_bytes.decode("utf-8")

        prompt = f"""
You are an expert static analysis software engineer.
Fix the unclosed resource leak identified below in the source code.

File: {file_path}
Line: {finding.line}
Resource: {finding.resource.type_name} '{finding.resource.var_name}'
Method: {finding.method_name}
Issue: {finding.message}

Full Source Code:
```
{source_text}
```

Instructions:
1. Provide ONLY the complete updated source code file wrapped in ```.
2. Make minimal changes to wrap the leaked resource in the appropriate language safe-resource idiom (e.g. try-with-resources for Java, defer for Go).
3. Do not add conversational text or markdown explanation.
"""

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
        )

        if not response or not response.text:
            return None

        new_code = response.text.strip()
        # Extract code block if wrapped in markdown
        if "```" in new_code:
            lines = new_code.splitlines()
            code_lines = []
            in_block = False
            for line in lines:
                if line.startswith("```"):
                    in_block = not in_block
                    continue
                if in_block:
                    code_lines.append(line)
            new_code = "\n".join(code_lines)

        if not new_code or new_code == source_text:
            return None

        # Build git diff
        import difflib
        from pathlib import Path
        file_name = Path(file_path).name
        orig_lines = source_text.splitlines(keepends=True)
        mod_lines = (new_code + "\n").splitlines(keepends=True)

        diff_lines = list(
            difflib.unified_diff(
                orig_lines,
                mod_lines,
                fromfile=f"a/{file_name}",
                tofile=f"b/{file_name}",
                n=3,
            )
        )
        return "".join(diff_lines) if diff_lines else None

    except Exception as err:
        return None
